sidebar_left_footer_links:
  default: >
    [
      {"title": "About Us", "url": "/about"},
      {"title": "Privacy Policy", "url": "/privacy"},
      {"title": "Terms of Service", "url": "/tos"}
    ]
  json_schema: >
    {
      "type": "array",
      "format": "table",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        },
        "required": ["title", "url"]
      }
    }
